### ISSUE TITLE
[bug] png图像没有透明显示，取消穿透有概率闪退

### ISSUE THREAD

**Issue by AliDva** [Ohto-Ai/PicturePin#9]
1.png图像不再显示透明的部分，png透明的部分将会变成白色像素覆盖屏幕，上一个版本没有该bug。
2.新加入的鼠标穿透功能在取消的时候有很大概率会闪退。

问题1截图：
0.1版本导入测试png图像
![image](https://user-images.githubusercontent.com/90774146/230249270-964d15de-43e2-4294-bbe4-f5f7a7c3122f.png)
现版本导入测试png图像
![image](https://user-images.githubusercontent.com/90774146/230249536-5cffb39a-53da-4aee-9e74-5ddec9fa8ad8.png)

**Comment by ohto-ai** [comment]
收到，下班后会测试下

**Comment by ohto-ai** [comment]
已解决，推送到 [v0.2.2](https://github.com/Ohto-Ai/ppin/releases/tag/v0.2.2) 版本
